#!/bin/bash

# Connect to teach.cs

if [ "$1" = "-y" ] # Graphical connection
then
	ssh -y harrisp5@teach.cs.toronto.edu
elif [ "$1" = "-s" ] # SQL server
then
  ssh harrisp5@dbsrv1.teach.cs.toronto.edu
else # Default
  ssh harrisp5@teach.cs.toronto.edu
fi
