#!/bin/bash

# Demote an old project or course to 'archive'

# Very specific to my filing system

# Usage: demote <code> <year> <semester>
#        demote <name>

TYPE=`pwd`
FP=$1
YEAR=$2'-year'
SEM=$3'-semester'
if [[ "$TYPE" =~ "courses" ]]
then
  DIR=$HOME/repos/courses/archive/$YEAR/$SEM
  mkdir -p $DIR
  mv $FP $DIR/$FP

elif [[ "$TYPE" =~ "current" ]]
then
  mv $FP $HOME/repos/archive/$FP
fi
