#!/bin/bash

state=`osascript -e 'tell application "Spotify" to player state as string'`;
if [ $state = "playing" ]; then
    artist=`osascript -e 'tell application "Spotify" to artist of current track as string'`;
    track=`osascript -e 'tell application "Spotify" to name of current track as string'`;

    echo "$artist - $track";
fi
