#!/bin/bash
HOME=/Users/patrickharris
SOURCES="$HOME/repos $HOME/important"
SEP="======================================================================"

# Command line wrapper for gitcheck.sh
for DIR in $SOURCES
do
    echo $SEP
    echo "Checking for uncommited changes in $DIR"
    echo $SEP
    echo ""
    pushd $DIR > /dev/null
    gitcheck.sh
    echo ""
    echo ""
    popd > /dev/null
done


