#!/bin/bash

cp -av /Users/patrickharris/.zshrc /Users/patrickharris/important/dotfiles

# Change the directory, commit to git, go back

function myprog() {
  cd /Users/patrickharris/important/dotfiles
	commit "Update zshrc"
	cd -
}
myprog
