#!/bin/bash
# At the start of each semester, create new directories for each course and intialize git
COURSES=$@

pushd $HOME/repos/courses > /dev/null

for i in $COURSES; do
    CUR="~courses/$i"
    mkdir -p $i
    pushd $i > /dev/null
    git init
    popd > /dev/null
    # Add a named directory to my rc file
    echo "export $i=$CUR" >> $HOME/.zshrc
done


