#!/bin/bash

# Connect to teach.cs. Make sure $UTORID is set up in current env

if [ "$1" = "-y" ] # Graphical connection
then
	ssh -y $UTORID@teach.cs.toronto.edu
elif [ "$1" = "-s" ] # SQL server
then
  ssh $UTORID@dbsrv1.teach.cs.toronto.edu
else # Default
  ssh $UTORID@teach.cs.toronto.edu
fi
